export const ADD_COUNT = 'ADD_COUNT'
export const ADD_COUNT2 = 'ADD_COUNT2'

export const SET_WAIT_DISPLAY = 'SET_WAIT_DISPLAY'

export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR'